include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    mixin_inherits_from_not_object: ignore
    public_member_api_docs: ignore
    package_api_docs: ignore
    slash_for_doc_comments: ignore

linter:
  rules:
    library_private_types_in_public_api: false
    constant_identifier_names: false
    library_prefixes: false
    avoid_print: false
    public_member_api_docs: false
    slash_for_doc_comments: false
    package_api_docs: false
    prefer_const_constructors: false
    prefer_const_constructors_in_immutables: false
    prefer_const_literals_to_create_immutables: false
    unnecessary_new: false
